# Generated by Django 2.1 on 2019-01-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_clientes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_clientes',
            name='cnpj',
            field=models.CharField(blank='True', max_length=14, null='True'),
        ),
        migrations.AlterField(
            model_name='tb_clientes',
            name='cpf',
            field=models.CharField(blank='True', max_length=12, null='True'),
        ),
    ]
