# Generated by Django 2.1 on 2018-09-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_equip',
            fields=[
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('modelo', models.CharField(blank='True', max_length=50, null='True')),
                ('marca', models.CharField(blank='True', max_length=50, null='True')),
                ('tensao', models.CharField(blank='True', max_length=6, null='True')),
                ('proxManu', models.DateField()),
                ('numSerie', models.CharField(blank='True', max_length=20, null='True')),
                ('fotoFrente', models.ImageField(blank='True', null='True', upload_to='Fotos_Equip')),
                ('fotoVerso', models.ImageField(blank='True', null='True', upload_to='Fotos_Equip')),
            ],
        ),
    ]
