# Generated by Django 2.1 on 2018-12-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_equip',
            fields=[
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('modelo', models.CharField(blank='True', max_length=50, null='True')),
                ('marca', models.CharField(blank='True', max_length=50, null='True')),
                ('tensao', models.CharField(blank='True', max_length=6, null='True')),
                ('proxManu', models.DateField()),
                ('numSerie', models.CharField(blank='True', max_length=20, null='True')),
                ('fotoFrente', models.ImageField(blank='True', null='True', upload_to='Fotos_Equip')),
                ('fotoVerso', models.ImageField(blank='True', null='True', upload_to='Fotos_Equip')),
            ],
        ),
        migrations.CreateModel(
            name='tb_orcamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEquip', models.CharField(max_length=20)),
                ('qtd', models.CharField(max_length=8)),
                ('valorUnit', models.CharField(max_length=8)),
            ],
        ),
    ]
