# Generated by Django 2.1 on 2018-11-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_equip_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_orcamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEquip', models.CharField(max_length=20)),
                ('qtd', models.CharField(max_length=8)),
                ('valorUnit', models.CharField(max_length=8)),
            ],
        ),
    ]
