# Generated by Django 2.1 on 2019-01-19 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cad_clientes_app', '0002_auto_20190118_1011'),
        ('cad_equip_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_equip',
            name='cliCod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cad_clientes_app.tb_clientes'),
        ),
        migrations.AlterField(
            model_name='tb_equip',
            name='modelo',
            field=models.CharField(blank='True', max_length=50, null='True', verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='tb_equip',
            name='numSerie',
            field=models.CharField(blank='True', max_length=20, null='True', verbose_name='Número de Série'),
        ),
        migrations.AlterField(
            model_name='tb_equip',
            name='proxManu',
            field=models.DateField(verbose_name='Próxima Manutenção'),
        ),
        migrations.AlterField(
            model_name='tb_equip',
            name='tensao',
            field=models.CharField(blank='True', max_length=6, null='True', verbose_name='Tensão'),
        ),
    ]
