# Generated by Django 2.1 on 2018-12-04 21:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cad_clientes_app', '0001_initial'),
        ('cad_equip_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.datetime_safe.datetime.now)),
                ('histReclamado', models.CharField(max_length=200)),
                ('hConstatado', models.CharField(max_length=200)),
                ('hServRealizado', models.CharField(max_length=200)),
                ('hEquipCod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cad_equip_app.tb_equip')),
            ],
        ),
        migrations.CreateModel(
            name='tb_os',
            fields=[
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('defReclamado', models.CharField(max_length=200, verbose_name='DEFEITO RECLAMADO')),
                ('defConstatado', models.CharField(max_length=200, verbose_name='DEFEITO CONSTATADO')),
                ('ServRealizado', models.CharField(max_length=200, verbose_name='SERVIÇO REALIZADO')),
                ('dataOs', models.DateField(auto_now_add=True)),
                ('dataInicioOs', models.DateField(verbose_name='DATA INICIAL')),
                ('dataFinalOs', models.DateField(verbose_name='DATA FINAL')),
                ('cliNome', models.CharField(blank='True', max_length=200, null='True')),
                ('cliCnpj', models.CharField(blank='True', max_length=14, null='True')),
                ('cliCpf', models.CharField(blank='True', max_length=12, null='True')),
                ('cliContato', models.CharField(blank='True', max_length=50, null='True')),
                ('cliCep', models.CharField(blank='True', max_length=8, null='True')),
                ('cliEndereco', models.CharField(blank='True', max_length=100, null='True')),
                ('cliBairro', models.CharField(blank='True', max_length=50, null='True')),
                ('cliCidade', models.CharField(blank='True', max_length=100, null='True')),
                ('cliUf', models.CharField(blank='True', max_length=2, null='True')),
                ('tipo_serv', models.CharField(choices=[('contrato', 'CONTRATO'), ('garantia', 'GARANTIA'), ('avulso', 'AVULSO')], max_length=8, verbose_name='SERVIÇO')),
                ('tipo_manut', models.CharField(choices=[('corretiva', 'CORRETIVA'), ('preventiva', 'PREVENTIVA')], max_length=10, verbose_name='MANUTENÇÃO')),
                ('tipo_aterramento', models.CharField(choices=[('sim', 'SIM'), ('nao', 'NÃO')], max_length=3, verbose_name='ATERRAMENTO')),
                ('status', models.CharField(blank='True', max_length=10, null='True', verbose_name='STATUS')),
                ('equipProxManu', models.DateField(verbose_name='PROX. MANUTENÇÃO')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='VALOR')),
                ('cliCod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cad_clientes_app.tb_clientes')),
                ('equipCod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cad_equip_app.tb_equip')),
            ],
        ),
        migrations.AddField(
            model_name='tb_historico',
            name='hOsCod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cad_ordemServ_app.tb_os'),
        ),
    ]
