# Generated by Django 2.1 on 2018-09-14 22:55

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('cad_ordemServ_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.datetime_safe.datetime.now)),
                ('histReclamado', models.CharField(max_length=200)),
                ('hConstatado', models.CharField(max_length=200)),
                ('hServRealizado', models.CharField(max_length=200)),
            ],
        ),
    ]
