# Generated by Django 2.1 on 2018-08-29 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cad_ordemServ_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_os',
            name='cliId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cad_clientes_app.tb_clientes'),
        ),
        migrations.AlterField(
            model_name='tb_os',
            name='equipId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cad_equip_app.tb_equip'),
        ),
    ]
