# Generated by Django 2.1 on 2018-08-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_ordemServ_app', '0002_auto_20180828_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_os',
            name='tipo_serv',
            field=models.CharField(choices=[('contrato', 'CONTRATO'), ('garantia', 'GARANTIA'), ('avulso', 'AVULSO')], default=1, max_length=8),
            preserve_default=False,
        ),
    ]
