# Generated by Django 2.1 on 2018-09-19 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cad_equip_app', '0001_initial'),
        ('cad_ordemServ_app', '0002_tb_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_historico',
            name='hEquipCod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cad_equip_app.tb_equip'),
        ),
    ]
