# Generated by Django 2.1 on 2018-08-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_ordemServ_app', '0003_tb_os_tipo_serv'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_os',
            name='tipo_aterramento',
            field=models.CharField(choices=[('sim', 'SIM'), ('nao', 'NÃO')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tb_os',
            name='tipo_manut',
            field=models.CharField(choices=[('corretiva', 'CORRETIVA'), ('preventiva', 'PREVENTIVA')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
