# Generated by Django 2.1 on 2018-09-19 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cad_ordemServ_app', '0003_tb_historico_hequipcod'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_historico',
            name='hOsCod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cad_ordemServ_app.tb_os'),
        ),
    ]
