# Generated by Django 2.1 on 2018-08-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_ordemServ_app', '0004_auto_20180829_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_os',
            name='id',
        ),
        migrations.AddField(
            model_name='tb_os',
            name='cod',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
