# Generated by Django 2.1 on 2018-10-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_ordemServ_app', '0004_tb_historico_hoscod'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_os',
            name='cliCnpj',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='tb_os',
            name='cliCpf',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='tb_os',
            name='cliNome',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tb_os',
            name='ServRealizado',
            field=models.CharField(max_length=200, verbose_name='SERVIÇO REALIZADO'),
        ),
        migrations.AlterField(
            model_name='tb_os',
            name='dataFinalOs',
            field=models.DateField(verbose_name='DATA FINAL'),
        ),
        migrations.AlterField(
            model_name='tb_os',
            name='dataInicioOs',
            field=models.DateField(verbose_name='DATA INICIAL'),
        ),
        migrations.AlterField(
            model_name='tb_os',
            name='defConstatado',
            field=models.CharField(max_length=200, verbose_name='DEFEITO CONSTATADO'),
        ),
        migrations.AlterField(
            model_name='tb_os',
            name='defReclamado',
            field=models.CharField(max_length=200, verbose_name='DEFEITO RECLAMADO'),
        ),
        migrations.AlterField(
            model_name='tb_os',
            name='tipo_aterramento',
            field=models.CharField(choices=[('sim', 'SIM'), ('nao', 'NÃO')], max_length=3, verbose_name='ATERRAMENTO'),
        ),
        migrations.AlterField(
            model_name='tb_os',
            name='tipo_manut',
            field=models.CharField(choices=[('corretiva', 'CORRETIVA'), ('preventiva', 'PREVENTIVA')], max_length=10, verbose_name='MANUTENÇÃO'),
        ),
        migrations.AlterField(
            model_name='tb_os',
            name='tipo_serv',
            field=models.CharField(choices=[('contrato', 'CONTRATO'), ('garantia', 'GARANTIA'), ('avulso', 'AVULSO')], max_length=8, verbose_name='SERVIÇO'),
        ),
    ]
