# Generated by Django 2.1 on 2018-10-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_ordemServ_app', '0005_auto_20181022_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_os',
            name='cliBairro',
            field=models.CharField(blank='True', max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='tb_os',
            name='cliCep',
            field=models.CharField(blank='True', max_length=8, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='tb_os',
            name='cliCidade',
            field=models.CharField(blank='True', max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='tb_os',
            name='cliContato',
            field=models.CharField(blank='True', max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='tb_os',
            name='cliEndereco',
            field=models.CharField(blank='True', max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='tb_os',
            name='cliUf',
            field=models.CharField(blank='True', max_length=2, null='True'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='tb_os',
            name='cliCnpj',
            field=models.CharField(blank='True', max_length=14, null='True'),
        ),
        migrations.AlterField(
            model_name='tb_os',
            name='cliCpf',
            field=models.CharField(blank='True', max_length=12, null='True'),
        ),
        migrations.AlterField(
            model_name='tb_os',
            name='cliNome',
            field=models.CharField(blank='True', max_length=200, null='True'),
        ),
    ]
