# Generated by Django 2.1 on 2018-08-29 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cad_ordemServ_app', '0005_auto_20180829_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_os',
            old_name='cliId',
            new_name='cliCod',
        ),
        migrations.RenameField(
            model_name='tb_os',
            old_name='equipId',
            new_name='equipCod',
        ),
    ]
