# Generated by Django 2.1 on 2018-11-13 23:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cad_ordemServ_app', '0007_tb_os_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_os',
            name='equipProxManu',
            field=models.DateField(default=datetime.datetime(2018, 11, 13, 23, 18, 32, 319624, tzinfo=utc), verbose_name='Proxima Manutenção'),
            preserve_default=False,
        ),
    ]
