# Generated by Django 2.1 on 2018-12-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_ordemServ_app', '0008_tb_os_equipproxmanu'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_os',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tb_os',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
            preserve_default=False,
        ),
    ]
