# Generated by Django 2.1 on 2018-12-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_ordemServ_app', '0009_auto_20181202_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_os',
            name='total',
            field=models.DecimalField(decimal_places=2, default=95, max_digits=5),
            preserve_default=False,
        ),
    ]
