# Generated by Django 2.1 on 2018-12-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_ordemServ_app', '0010_tb_os_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_os',
            name='desconto',
        ),
        migrations.RemoveField(
            model_name='tb_os',
            name='total',
        ),
        migrations.AlterField(
            model_name='tb_os',
            name='equipProxManu',
            field=models.DateField(verbose_name='PROX. MANUTENÇÃO'),
        ),
        migrations.AlterField(
            model_name='tb_os',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='VALOR'),
        ),
    ]
