# Generated by Django 2.1 on 2018-12-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad_ordemServ_app', '0011_auto_20181202_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_os',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='VALOR'),
        ),
    ]
